// layout 과 관련된 부분
export const setDrawer = "setDrawer";
export const setSetting = "setSetting";
export const setAlert = "SET_ALERT";
export const setSearchResult = "SET_SEARCH_RESULT";
export const setModal = "SET_MODAL";
export const SELECT_MEMBER = "SELECT_MEMBER";
export const DELETE_MEMBER = "DELETE_MEMBER";
export const UPDATE_MEMBER = "UPDATE_MEMBER";
export const DETAILS_MEMBER = "DETAILS_MEMBER";