version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15

executors:
  node:
    docker:
      - image: circleci/node:10

jobs:
  build_and_deploy:
    executor: node
    steps:
      - checkout
      - run: npm install
      - run: npm audit fix
      - run: npm run build:prod
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-region: AWS_REGION
          from: ./dist
          overwrite: true
          to: "s3://nnnn.code2world.xyz"
      - run: aws cloudfront create-invalidation --distribution-id E1PYPHG3UU5VDH --paths "/*"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
