version: 2.1
orbs:
  aws-s3: circleci/aws-s3@1.0.15

executors:
  node:
    docker:
      - image: circleci/node:10

jobs:
  build_and_deploy:
    executor: node
    steps:
      - checkout
       - run:
          name: Installing AWS CLI
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install -y awscli
            sudo apt-get install -y python-pip python-dev build-essential
            sudo pip install awscli --upgrade
      - run:
         name: Preparing Artifact
          command: |
            npm install
            npm audit fix
            npm run build:prod
            
      - aws-s3/sync:
          arguments: |
            --acl public-read \
            --cache-control "max-age=86400"
          aws-region: AWS_REGION
          from: ./dist
          overwrite: true
          to: "s3://nnnn.code2world.xyz"
      - run: aws cloudfront create-invalidation --distribution-id E1PYPHG3UU5VDH --paths "/*"

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_deploy:
          filters:
            branches:
              only: master
